trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - user-app
    exclude:
      - README.md
      - CHANGELOG.md
      - Makefile
      - user-app/azure-pipelines-db.yml
      - user-app/azure-pipelines.yml

resources:
  repositories:
    - repository: default
      type: git
      name: microservice-theworld

variables:
  - group: common-vars
    
pool:
  vmImage: $(POOL_IMAGE)

steps:
  - template: templates/step-ng-ecr-ci.yml@default
    parameters:
      path: user-app
      serviceName: user_app
      dockerFile: templates/Dockerfile
  - template: templates/step-auto-pl-ci.yml@default
    parameters:
      repoName: microservice-theinfra
      filePath: /prod/service-user/IMAGE
      fileContent: $(IMAGE_VERSION)